### PR TITLE
feat: update config

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Update some of the config so that users can get correct author and repo.

Also, you should only enable features you need in `mdEnhance`, I am not sure about your files, so I only deleted ones you absolutely not in use. Removing others can help increasing web page performance and build speed.

**Comment by Mister-Hope** [comment]
Also this is a very nice customization, if you don't mind, I will add this one to project list in theme docs.

**Review by VampireAchao — APPROVED** [review]
LGTM

**Review by VampireAchao — CHANGES_REQUESTED** [review]
.

**Review by VampireAchao — APPROVED** [review]
.

**Pull request merged**
